version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/user/src/my-app/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
