### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm


### GET request to domain root for testing
GET http://localhost:4000


### GET check a messages array
GET http://localhost:4000/messages


### POST check a messages array
POST http://localhost:4000/messages
Content-Type: application/json

{
  "message": "redis test"
}

### fibonacci function to load a lot
GET http://localhost:4000/fibonacci/10
